config/routes.rb
Rails.application.routes.draw do
  resources :noticia
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/noticium.rb
class Noticium
  include Mongoid::Document
  field :description, type: String
  field :datepost, type: Date
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/noticia_controller.rb
class NoticiaController < ApplicationController
  before_action :set_noticium, only: [:show, :edit, :update, :destroy]

  # GET /noticia
  # GET /noticia.json
  def index
    @noticia = Noticium.all
  end

  # GET /noticia/1
  # GET /noticia/1.json
  def show
  end

  # GET /noticia/new
  def new
    @noticium = Noticium.new
  end

  # GET /noticia/1/edit
  def edit
  end

  # POST /noticia
  # POST /noticia.json
  def create
    @noticium = Noticium.new(noticium_params)

    respond_to do |format|
      if @noticium.save
        format.html { redirect_to @noticium, notice: 'Noticium was successfully created.' }
        format.json { render :show, status: :created, location: @noticium }
      else
        format.html { render :new }
        format.json { render json: @noticium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /noticia/1
  # PATCH/PUT /noticia/1.json
  def update
    respond_to do |format|
      if @noticium.update(noticium_params)
        format.html { redirect_to @noticium, notice: 'Noticium was successfully updated.' }
        format.json { render :show, status: :ok, location: @noticium }
      else
        format.html { render :edit }
        format.json { render json: @noticium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /noticia/1
  # DELETE /noticia/1.json
  def destroy
    @noticium.destroy
    respond_to do |format|
      format.html { redirect_to noticia_url, notice: 'Noticium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_noticium
      @noticium = Noticium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def noticium_params
      params.require(:noticium).permit(:description, :datepost)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/noticia_helper.rb
module NoticiaHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Post</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/noticia/_form.html.erb
<%= form_with(model: noticium, local: true) do |form| %>
  <% if noticium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(noticium.errors.count, "error") %> prohibited this noticium from being saved:</h2>

      <ul>
      <% noticium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :datepost %>
    <%= form.text_field :datepost %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/noticia/edit.html.erb
<h1>Editing Noticium</h1>

<%= render 'form', noticium: @noticium %>

<%= link_to 'Show', @noticium %> |
<%= link_to 'Back', noticia_path %>

app/views/noticia/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Noticia</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Datepost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @noticia.each do |noticium| %>
      <tr>
        <td><%= noticium.description %></td>
        <td><%= noticium.datepost %></td>
        <td><%= link_to 'Show', noticium %></td>
        <td><%= link_to 'Edit', edit_noticium_path(noticium) %></td>
        <td><%= link_to 'Destroy', noticium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Noticium', new_noticium_path %>

app/views/noticia/new.html.erb
<h1>New Noticium</h1>

<%= render 'form', noticium: @noticium %>

<%= link_to 'Back', noticia_path %>

app/views/noticia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @noticium.description %>
</p>

<p>
  <strong>Datepost:</strong>
  <%= @noticium.datepost %>
</p>

<%= link_to 'Edit', edit_noticium_path(@noticium) %> |
<%= link_to 'Back', noticia_path %>